server:
  port: 8087
hm:
  db:
    database: hm-item
  swagger:
    title: "搜索服务接口文档"
    package: com.hmall.search.controller
spring:
  rabbitmq:
    host: 192.168.200.130
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123