server:
  port: 8089
hm:
  db:
    database: hm-item
  swagger:
    title: "黑马商城商品服务接口文档"
    package: com.hmall.item.controller
spring:
  rabbitmq:
    host: 192.168.200.130
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123